version: "2.4"

services:
  odoo:
    image: openspp/openspp:15.0
    build:
      context: ./odoo
      args:
        ODOO_VERSION: "15.0"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    environment:
      EMAIL_FROM: "contact@openspp.org"
      PGDATABASE: &dbname prod
      PGUSER: &dbuser "odoo"
      PROXY_MODE: "true"
      LIST_DB: "True"
    tty: true
    volumes:
      - filestore:/var/lib/odoo:z
    labels:
      traefik.backend.buffering.retryExpression: IsNetworkError() && Attempts() < 5
      traefik.docker.network: "inverseproxy_shared"
      traefik.frontend.passHostHeader: "true"
      traefik.port: "8069"
  odoo-celery:
    volumes:
      # Host paths (odoo modules, src code & conf)
      - ./odoo/custom:/opt/odoo/custom:ro,z
    environment:
      - LOG_LEVEL=debug

  db:
    image: ghcr.io/tecnativa/postgres-autoconf:13-alpine
    shm_size: 4gb
    environment:
      POSTGRES_DB: *dbname
      POSTGRES_USER: *dbuser
      CONF_EXTRA: |
        work_mem = 512MB
    volumes:
      - db:/var/lib/postgresql/data:z

  smtpfake:
    image: docker.io/mailhog/mailhog

  backup:
    image: ghcr.io/tecnativa/docker-duplicity-postgres-s3:latest
    hostname: backup
    domainname: demo.openspp.org
    init: true
    environment:
      DBS_TO_INCLUDE: "^prod"
      DST: "boto3+s3://example_bucket"
      PGDATABASE: *dbname
      PGUSER: *dbuser
      TZ: "UTC"
    volumes:
      - backup_cache:/root:z
      - filestore:/mnt/backup/src/odoo:z
